### ISSUE TITLE
问题：对于官网测试用例的测试

### ISSUE THREAD

**Issue by rid-sun** [nzh63/syc#1]
您好，对于如下面图片所示的源代码，出现了似乎不能编译的情况（见第二张图片）
![图1](https://user-images.githubusercontent.com/34058427/117674219-10582400-b1de-11eb-97eb-3e96fb4c9b33.png)
![图2](https://user-images.githubusercontent.com/34058427/117676379-13541400-b1e0-11eb-9e56-1759809b344a.png)
我也没有修改您的代码，直接拿来跑一下。看这情况应该是语法分析部分出了问题也或许是其他方面我的原因，想问一下您有没有解决的思路。

**Comment by nzh63** [comment]
这个测试用例我们之前也是[测过的](https://github.com/nzh63/syc/blob/master/test/functional_test/15_array_test3.sy)，我这边检查了以下是没有问题的，不论是本地还是[Live demo](https://nzh63.github.io/syc/)。

看输出应该是有特殊空格，建议检查一下有没有不可见字符。

**Comment by rid-sun** [comment]
您好，我复制粘贴了之后，仍然是出现了这个题。很是奇怪。我的环境配置如下：
cmake版本是3.20.0，flex版本是2.6.4，bison版本是3.0.4，Ubuntu版本是18.04.05，c/c++版本是7.5.0。
会不会是这个环境配置问题呢？

**Comment by rid-sun** [comment]
> 
> 
> 这个测试用例我们之前也是[测过的](https://github.com/nzh63/syc/blob/master/test/functional_test/15_array_test3.sy)，我这边检查了以下是没有问题的，不论是本地还是[Live demo](https://nzh63.github.io/syc/)。
> 
> 看输出应该是有特殊空格，建议检查一下有没有不可见字符。

您好，我复制粘贴了之后（包括自己在虚拟机上去手打输入这个文件），仍然是出现了这个题。很是奇怪。但是如果把它们放在一行就不会出现问题了，之后便想到linux和windows中，回车换行的区别。于是将tokens.l中的\n改成\r便成功了。
最后感谢回复，祝学业有成、工作顺利！
